using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Simcraft
{
    enum stat_e
    {
        STAT_NONE = 0,
        STAT_STRENGTH, STAT_AGILITY, STAT_STAMINA, STAT_INTELLECT, STAT_SPIRIT,
        STAT_AGI_INT, STAT_STR_AGI, STAT_STR_INT, STAT_STR_AGI_INT,
        STAT_HEALTH, STAT_MANA, STAT_RAGE, STAT_ENERGY, STAT_FOCUS, STAT_RUNIC,
        STAT_MAX_HEALTH, STAT_MAX_MANA, STAT_MAX_RAGE, STAT_MAX_ENERGY, STAT_MAX_FOCUS, STAT_MAX_RUNIC,
        STAT_SPELL_POWER,
        STAT_ATTACK_POWER, STAT_EXPERTISE_RATING, STAT_EXPERTISE_RATING2,
        STAT_HIT_RATING, STAT_HIT_RATING2, STAT_CRIT_RATING, STAT_HASTE_RATING, STAT_MASTERY_RATING,
        STAT_WEAPON_DPS,
        STAT_WEAPON_OFFHAND_DPS,
        STAT_ARMOR, STAT_BONUS_ARMOR, STAT_RESILIENCE_RATING, STAT_DODGE_RATING, STAT_PARRY_RATING,
        STAT_BLOCK_RATING, STAT_PVP_POWER,
        STAT_MULTISTRIKE_RATING, STAT_READINESS_RATING, STAT_VERSATILITY_RATING, STAT_LEECH_RATING,
        STAT_SPEED_RATING, STAT_AVOIDANCE_RATING,
        STAT_ALL,
        STAT_MAX
    };
}
